### ISSUE TITLE
Use source package name instead of binary packages on Debian-based distributions

### ISSUE THREAD

**Issue by thomas-moulard** [tannewt/open-source-watershed#2]
If possible, it would be cool to use source package name (available in the "source:" on Debian for instance) to merge all the binary packages together.

```
$ apt-cache search '^libxml2-'
libxml2-dbg - Debugging symbols for the GNOME XML library
libxml2-dev - Development files for the GNOME XML library
libxml2-doc - Documentation for the GNOME XML library
libxml2-utils - XML utilities
libxml2-dbgsym - debug symbols for package libxml2
libxml2-udeb-dbgsym - debug symbols for package libxml2-udeb
libxml2-utils-dbgsym - debug symbols for package libxml2-utils
```

But if you run:

```
$ apt-cache search '^libxml2-' | cut -d' ' -f1 | xargs apt-cache show | grep Source
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
Source: libxml2
```

It would be much easier if we could see the versions per upstream package and not per binary package (on Debian, all binary it is not allowed to have per-package versioning scheme anyway, the version number is the same if the source package is identical).

**Comment by tannewt** [comment]
I ran a one time link step between all of these already. Thats why you can still compare the Debian specific libxml2-dev to libxml2 in other distros. How would you change the UI to make this more obvious?

**Comment by thomas-moulard** [comment]
I see, actually it is not working for some of my packages:

Here you can see that the Debian specific ones are not linked:
http://oswatershed.org/search?q=roboptim-core

And here the ABI broke so we have both libvisp2 (2.7) and libvisp2.8:
http://oswatershed.org/search?q=visp

IMHO what I would do is only list sources (upstream) packages on the website, then when one clicks on one package for each distro the binary packages could be listed.
Remembering the alternative namings could be useful if the users inputs a binary package name and not a source package name. The search algorithm could accept that...

(I don't know the code base so I am not sure if it is easily doable or not)

**Comment by tannewt** [comment]
Ok, I can do another one-off import if I have time this weekend.

I'm still not sure what I want to do about search so I'll do that second if
at all.

**Comment by thomas-moulard** [comment]
Thank you! :)

**Comment by tannewt** [comment]
Ok, I did another one-off import and it looks like your packages have been linked. FYI the script doing the import is here: https://github.com/tannewt/open-source-watershed/blob/live/crawl/scripts/source_crawl.py
