### ISSUE TITLE
FreeBSD 10 does not show

### ISSUE THREAD

**Issue by lantw44** [tannewt/open-source-watershed#3]
FreeBSD 10.0-RELEASE should be the latest release of FreeBSD, but the web page still shows FreeBSD 9 as current release.

**Comment by tannewt** [comment]
Do you know where the ports are kept for it? I'm scraping from here: http://ftp.freebsd.org/pub/FreeBSD/ports/amd64/

The code that scrapes is here: https://github.com/tannewt/open-source-watershed/blob/live/crawl/distros/freebsd.py

**Comment by lantw44** [comment]
FreeBSD pkgng repositories: http://pkg.freebsd.org/

**Comment by lantw44** [comment]
Reading the json file called `packagesite.yaml` inside `packagesite.txz` should be the right way to get information from the official pkgng repository (http://pkg.freebsd.org/). The old pkg_add tool, which uses http://ftp.freebsd.org/pub/FreeBSD/ports/amd64/, is no longer supported.

**Comment by tannewt** [comment]
Ok, I'll take a look now. Thanks for the info. Its interesting to see a new package manager.

**Comment by tannewt** [comment]
I've got it mostly going. Which packagesite should I use? Right now I'm using release_0 and release_1 from http://pkg.freebsd.org/freebsd:10:x86:64/ but it looks like the one in latest/ is more up to date. Would a 10.0 user be using the packages from latest? What is latest used for?

**Comment by lantw44** [comment]
I guess that  release_0 and release_1 are packages which are built when FreeBSD 10.0 and 10.1 is released, respectively. I think we should track latest, which is built at least once a week. It is also the default on newly-installed FreeBSD systems.
