### ISSUE TITLE
Installation manual

### ISSUE THREAD

**Issue by hoehnp** [tannewt/open-source-watershed#6]
Hi Scott,

first of all thank you for  this nice project. I always enjoyed watching the status of packages on the oswatershed website. As this website seems now abandoned could you please provide a manual about how to setup the code of open-source-watershed on an own server?

**Comment by tannewt** [comment]
Start with crawl.py to scrape data, https://github.com/tannewt/open-source-watershed/blob/live/crawl/scripts/create_db.py to make the database and https://github.com/tannewt/open-source-watershed/blob/live/site/oswatershed/manage.py to start the website. Besides that, I can't give you much help. I haven't set it up in a long time.
